const $=id=>document.getElementById(id);const norm=s=>String(s||'').toLowerCase().replace(/[’']/g,"'").replace(/_/g,' ').replace(/\s+/g,' ').trim();
const aliases={'kishoreganj':'kishorganj','kishore gonj':'kishorganj','pakshi':'paksey','pakshi railway':'paksey','jessore':'jashore','comilla':'cumilla','commilla':'cumilla','kustia court':'kushtia court','kushtia_court':'kushtia court'};
let result=null, calendar=new Date(), chosen=null;
function stationMatches(q){q=norm(q);const c=aliases[q]||q;return [...new Set(STATIONS)].filter(s=>!q||norm(s).includes(q)||norm(s).includes(c)).slice(0,30)}
function trainMatches(q){q=norm(q);return TRAINS.filter(([n,name])=>!q||String(n).includes(q)||norm(name).includes(q)).slice(0,30)}
function menu(input,box,items,onPick){box.innerHTML=items.map(x=>`<div class="item" data-v="${encodeURIComponent(x.v)}"><b>${x.title}</b>${x.sub?`<span>${x.sub}</span>`:''}</div>`).join('');box.classList.toggle('open',items.length>0);box.querySelectorAll('.item').forEach(el=>el.onclick=()=>{onPick(decodeURIComponent(el.dataset.v));box.classList.remove('open')})}
$('from').oninput=()=>menu($('from'),$('fromMenu'),stationMatches($('from').value).map(v=>({v,title:v})),v=>$('from').value=v);
$('to').oninput=()=>menu($('to'),$('toMenu'),stationMatches($('to').value).map(v=>({v,title:v})),v=>$('to').value=v);
$('train').oninput=()=>menu($('train'),$('trainMenu'),trainMatches($('train').value).map(([n,name])=>({v:String(n),title:`${name} (${n})`,sub:`Train number ${n}`})),v=>{const hit=TRAINS.find(([n])=>String(n)===v);$('train').value=hit?`${hit[1]} (${hit[0]})`:v});
document.addEventListener('click',e=>{if(!e.target.closest('.combo'))document.querySelectorAll('.menu').forEach(x=>x.classList.remove('open'))});
function parsedTrain(){const raw=$('train').value.trim();const m=raw.match(/\b\d{3,4}\b/);if(m){const hit=TRAINS.find(([n])=>String(n)===m[0]);return {model:m[0],trip:hit?`${hit[1].toUpperCase()} (${m[0]})`:m[0],display:hit?`${hit[1]} (${m[0]})`:raw}}const n=norm(raw);const hit=TRAINS.find(([no,name])=>norm(name)===n||norm(name).includes(n)||n.includes(norm(name)));return hit?{model:String(hit[0]),trip:`${hit[1].toUpperCase()} (${hit[0]})`,display:`${hit[1]} (${hit[0]})`}:null}
function fmt(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function hero(d){return d.toLocaleDateString('en-US',{weekday:'short',month:'short',day:'2-digit',year:'numeric'})}
function renderCal(){const y=calendar.getFullYear(),m=calendar.getMonth();$('month').textContent=calendar.toLocaleDateString('en-US',{month:'long',year:'numeric'});$('heroYear').textContent=chosen?chosen.getFullYear():y;$('heroDate').textContent=chosen?hero(chosen):'Select journey date';const first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate();let h='';for(let i=0;i<first;i++)h+='<div class="empty"></div>';for(let d=1;d<=days;d++){const active=chosen&&chosen.getFullYear()===y&&chosen.getMonth()===m&&chosen.getDate()===d;h+=`<button class="day ${active?'active':''}" data-d="${d}">${d}</button>`}$('grid').innerHTML=h;$('grid').querySelectorAll('.day').forEach(b=>b.onclick=()=>{chosen=new Date(y,m,Number(b.dataset.d));$('date').value=fmt(chosen);$('datePicker').classList.remove('open')})}
$('date').onclick=()=>{const cur=$('date').value?new Date($('date').value+'T00:00:00'):new Date();if(!chosen)chosen=cur;calendar=new Date(chosen);renderCal();$('datePicker').classList.add('open')};$('prev').onclick=()=>{calendar.setMonth(calendar.getMonth()-1);renderCal()};$('next').onclick=()=>{calendar.setMonth(calendar.getMonth()+1);renderCal()};$('datePicker').onclick=e=>{if(e.target===$('datePicker'))$('datePicker').classList.remove('open')};
function setStatus(t,error=false){$('status').textContent=t;$('status').classList.toggle('error',error)}
function render(data){result=data;$('result').hidden=false;$('title').textContent=data.request.display;$('route').textContent=`${data.request.from} → ${data.request.to}`;$('loadedAt').textContent=`Updated ${new Date().toLocaleTimeString()}`;const classes=[...new Set(data.pairs.flatMap(p=>Object.keys(p.classes||{})))];$('cls').innerHTML='<option value="">All classes</option>'+classes.map(c=>`<option>${c}</option>`).join('');draw()}
function draw(){if(!result)return;const cls=$('cls').value,filter=norm($('filter').value),pairs=result.pairs.filter(p=>!filter||norm(p.origin).includes(filter)||norm(p.dest).includes(filter));const stations=[...new Set(pairs.flatMap(p=>[p.origin,p.dest]))];let h='<div class="matrix"><table><thead><tr><th>STATION</th>'+stations.map(s=>`<th>${s}</th>`).join('')+'</tr></thead><tbody>';for(const s of stations){h+=`<tr><td>${s}</td>`;for(const t of stations){const p=pairs.find(x=>x.origin===s&&x.dest===t);let val=0;if(p){const cs=cls&&p.classes[cls]?[p.classes[cls]]:Object.values(p.classes||{});val=cs.reduce((a,c)=>a+Number(c.total||0),0)}h+=`<td><span class="cell ${val?'has':'zero'}">${val||'—'}</span></td>`}h+='</tr>'}h+='</tbody></table></div>';$('matrix').innerHTML=h}
async function load(){const tr=parsedTrain(),from=$('from').value.trim(),to=$('to').value.trim(),date=$('date').value;if(!from||!to||!date||!tr){setStatus('Enter valid From, To, Date and Train.',true);return}$('load').disabled=true;setStatus('Loading live seat matrix…');try{const q=new URLSearchParams({from,to,date,trainModel:tr.model,tripNumber:tr.trip,display:tr.display});const r=await fetch('/api/matrix?'+q);const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'Matrix request failed');render(j.data);setStatus('Live matrix loaded.')}catch(e){setStatus(e.message||'Unable to load matrix.',true)}finally{$('load').disabled=false}}
$('load').onclick=load;$('refresh').onclick=load;$('cls').onchange=draw;$('filter').oninput=draw;
