function clean(v){return String(v||'').replaceAll('_',' ').replace(/\s+/g,' ').trim()}
function norm(v){return clean(v).toLowerCase().replace(/[’']/g,"'")}
function balancedObject(s,start){let depth=0,inStr=false,esc=false;for(let i=start;i<s.length;i++){const c=s[i];if(inStr){if(esc)esc=false;else if(c==='\\')esc=true;else if(c==='"')inStr=false}else{if(c==='"')inStr=true;else if(c==='{')depth++;else if(c==='}'&&--depth===0)return s.slice(start,i+1)}}throw new Error('Could not parse RailMatrix data.')}
function extractInitialData(html){const decoded=[];const re=/self\.__next_f\.push\(\[1,\s*("(?:\\.|[^"\\])*")\]\)/g;let m;while((m=re.exec(html))){try{decoded.push(JSON.parse(m[1]))}catch{}}const text=decoded.join('\n');for(const marker of ['"initialData":','\\"initialData\\":']){const start=text.indexOf(marker);if(start<0)continue;let i=start+marker.length;while(/\s/.test(text[i]))i++;if(text[i]!=='{')continue;try{return JSON.parse(balancedObject(text,i))}catch{}}throw new Error('RailMatrix initialData was not found.')}
function buildMatrix(data,from,to,date,trainModel,tripNumber,display){const routes=data.routes||[],pairs=[],stations=[],seen=new Set();for(const r of routes){const origin=clean(r.origin),dest=clean(r.desti||r.destination);if(!origin||!dest)continue;if(!seen.has(origin)){seen.add(origin);stations.push(origin)}if(!seen.has(dest)){seen.add(dest);stations.push(dest)}const trains=r.trains||[];const selected=trains.filter(t=>String(t.train_model||'')===String(trainModel)||norm(t.trip_number)===norm(tripNumber));const use=selected.length?selected:trains.filter(t=>String(t.train_model||'')===String(trainModel));const classes={};for(const t of use){const cls=t.seat_class||t.seat_type;if(!cls)continue;const c=t.seat_counts||{};classes[cls]={online:Number(c.online||0),offline:Number(c.offline||0),total:Number(t.final_seat_count??((c.online||0)+(c.offline||0))),fare:t.final_fare??t.fare??null}}pairs.push({origin,dest,classes})}return{meta:data.meta||{},request:{from,to,date,trainModel,tripNumber,display:display||tripNumber},stations,pairs}}
export default async function handler(req,res){
  if(req.method!=='GET'){res.status(405).json({ok:false,error:'Method not allowed'});return}
  const {from,to,date,trainModel,tripNumber,display}=req.query||{};
  if(!from||!to||!date||!trainModel){res.status(400).json({ok:false,error:'from, to, date and trainModel are required'});return}
  const variants=[]; const add=(tm,tn)=>{const u=`https://railmatrix.syntaxcube.com/trains/${encodeURIComponent(tm)}?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}&date=${encodeURIComponent(date)}&train_model=${encodeURIComponent(tm)}&trip_number=${encodeURIComponent(tn||'')}`;if(!variants.some(x=>x.url===u))variants.push({url:u,tm,tn})};
  add(trainModel,tripNumber); add(trainModel,String(trainModel)); const no=String(trainModel).match(/\d{3,4}/)?.[0]; if(no){add(no,tripNumber||no);add(no,no);add(no,'')}
  let last='RailMatrix data could not be loaded.';
  for(const v of variants){try{const r=await fetch(v.url,{headers:{'user-agent':'Mozilla/5.0'},cache:'no-store'});if(!r.ok){last=`RailMatrix HTTP ${r.status}`;continue}const html=await r.text();const data=extractInitialData(html);if(data?.routes?.length){const built=buildMatrix(data,from,to,date,v.tm,v.tn,display);if(built.pairs.length){res.setHeader('Cache-Control','s-maxage=15, stale-while-revalidate=30');res.status(200).json({ok:true,data:built,source:'RailMatrix'});return}}last='No route data returned'}catch(e){last=e?.message||String(e)}}
  res.status(502).json({ok:false,error:last});
}
